/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ApiProjectsRouteImport } from "./routes/api/projects";
import { Route as ApiProfileRouteImport } from "./routes/api/profile";
import { Route as ApiExperienceRouteImport } from "./routes/api/experience";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: "/api/projects",
  path: "/api/projects",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: "/api/profile",
  path: "/api/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiExperienceRoute = ApiExperienceRouteImport.update({
  id: "/api/experience",
  path: "/api/experience",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/api/experience": typeof ApiExperienceRoute;
  "/api/profile": typeof ApiProfileRoute;
  "/api/projects": typeof ApiProjectsRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/api/experience": typeof ApiExperienceRoute;
  "/api/profile": typeof ApiProfileRoute;
  "/api/projects": typeof ApiProjectsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/api/experience": typeof ApiExperienceRoute;
  "/api/profile": typeof ApiProfileRoute;
  "/api/projects": typeof ApiProjectsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/api/experience" | "/api/profile" | "/api/projects";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/api/experience" | "/api/profile" | "/api/projects";
  id: "__root__" | "/" | "/api/experience" | "/api/profile" | "/api/projects";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ApiExperienceRoute: typeof ApiExperienceRoute;
  ApiProfileRoute: typeof ApiProfileRoute;
  ApiProjectsRoute: typeof ApiProjectsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/projects": {
      id: "/api/projects";
      path: "/api/projects";
      fullPath: "/api/projects";
      preLoaderRoute: typeof ApiProjectsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/profile": {
      id: "/api/profile";
      path: "/api/profile";
      fullPath: "/api/profile";
      preLoaderRoute: typeof ApiProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/experience": {
      id: "/api/experience";
      path: "/api/experience";
      fullPath: "/api/experience";
      preLoaderRoute: typeof ApiExperienceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiExperienceRoute: ApiExperienceRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiProjectsRoute: ApiProjectsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
