/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiExperienceRouteImport } from './routes/api/experience'
import { Route as ApiBlogsRouteImport } from './routes/api/blogs'
import { Route as ApiGithubStatsRouteImport } from './routes/api/github/stats'
import { Route as ApiBlogsSlugRouteImport } from './routes/api/blogs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExperienceRoute = ApiExperienceRouteImport.update({
  id: '/api/experience',
  path: '/api/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogsRoute = ApiBlogsRouteImport.update({
  id: '/api/blogs',
  path: '/api/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubStatsRoute = ApiGithubStatsRouteImport.update({
  id: '/api/github/stats',
  path: '/api/github/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogsSlugRoute = ApiBlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiBlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/blogs': typeof ApiBlogsRouteWithChildren
  '/api/experience': typeof ApiExperienceRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/blogs/$slug': typeof ApiBlogsSlugRoute
  '/api/github/stats': typeof ApiGithubStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/blogs': typeof ApiBlogsRouteWithChildren
  '/api/experience': typeof ApiExperienceRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/blogs/$slug': typeof ApiBlogsSlugRoute
  '/api/github/stats': typeof ApiGithubStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/blogs': typeof ApiBlogsRouteWithChildren
  '/api/experience': typeof ApiExperienceRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/blogs/$slug': typeof ApiBlogsSlugRoute
  '/api/github/stats': typeof ApiGithubStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/blogs'
    | '/api/experience'
    | '/api/profile'
    | '/api/projects'
    | '/api/blogs/$slug'
    | '/api/github/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/blogs'
    | '/api/experience'
    | '/api/profile'
    | '/api/projects'
    | '/api/blogs/$slug'
    | '/api/github/stats'
  id:
    | '__root__'
    | '/'
    | '/api/blogs'
    | '/api/experience'
    | '/api/profile'
    | '/api/projects'
    | '/api/blogs/$slug'
    | '/api/github/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBlogsRoute: typeof ApiBlogsRouteWithChildren
  ApiExperienceRoute: typeof ApiExperienceRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiGithubStatsRoute: typeof ApiGithubStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/experience': {
      id: '/api/experience'
      path: '/api/experience'
      fullPath: '/api/experience'
      preLoaderRoute: typeof ApiExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blogs': {
      id: '/api/blogs'
      path: '/api/blogs'
      fullPath: '/api/blogs'
      preLoaderRoute: typeof ApiBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/stats': {
      id: '/api/github/stats'
      path: '/api/github/stats'
      fullPath: '/api/github/stats'
      preLoaderRoute: typeof ApiGithubStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blogs/$slug': {
      id: '/api/blogs/$slug'
      path: '/$slug'
      fullPath: '/api/blogs/$slug'
      preLoaderRoute: typeof ApiBlogsSlugRouteImport
      parentRoute: typeof ApiBlogsRoute
    }
  }
}

interface ApiBlogsRouteChildren {
  ApiBlogsSlugRoute: typeof ApiBlogsSlugRoute
}

const ApiBlogsRouteChildren: ApiBlogsRouteChildren = {
  ApiBlogsSlugRoute: ApiBlogsSlugRoute,
}

const ApiBlogsRouteWithChildren = ApiBlogsRoute._addFileChildren(
  ApiBlogsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBlogsRoute: ApiBlogsRouteWithChildren,
  ApiExperienceRoute: ApiExperienceRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiGithubStatsRoute: ApiGithubStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
